### ISSUE TITLE
添加processing.js支持

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/flower-power#3]
支持渲染成HTML canvas

**Comment by at15** [comment]
:dog:

**Comment by gaocegege** [comment]
你何苦天天来吃狗粮呢

**Comment by at15** [comment]
因为没到午饭就饿了

**Comment by at15** [comment]
又出现在了 timeline 上....

**Comment by gaocegege** [comment]
Because I'm trying to apply for processing again.

**Comment by at15** [comment]
well ... I should make a chrome plugin to automatically add :dog: when this kind of things shows up in my timeline

**Comment by gaocegege** [comment]
CNCF is on my waiting list because ... We could chat privately.

I'll file two proposals maybe. One for coala and other for processing.
